[package]
name = "gsm_interface"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/gsm_interface.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
